<?php
/**
 * DocumentServiceApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * DocumentServiceApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class DocumentServiceApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for generateKekosPrintingPage
     *
     * Wydruk Karty Ewidencji Komunalnych Osadów Ściekowych.
     *
     */
    public function testGenerateKekosPrintingPage()
    {
    }

    /**
     * Test case for generateKekosReaserchPrintingPage
     *
     * Wydruk Karty Badań Komunalnych Osadów Ściekowych.
     *
     */
    public function testGenerateKekosReaserchPrintingPage()
    {
    }

    /**
     * Test case for generateKeoPrintingPage
     *
     * Wydruk Karty Ewidencji Odpadów.
     *
     */
    public function testGenerateKeoPrintingPage()
    {
    }

    /**
     * Test case for generateKeokPrintingPage
     *
     * Wydruk Karty Ewidencji Odpadów Komunalnych.
     *
     */
    public function testGenerateKeokPrintingPage()
    {
    }

    /**
     * Test case for generateKeonPrintingPage
     *
     * Wydruk Karty Ewidencji Odpadów Niebezpiecznych.
     *
     */
    public function testGenerateKeonPrintingPage()
    {
    }

    /**
     * Test case for generateKepwCollectingPrintingPage
     *
     * Wydruk Karty Ewidencji Pojazdów Wycofanych z Eksploatacji z punktu zbierania pojazdów.
     *
     */
    public function testGenerateKepwCollectingPrintingPage()
    {
    }

    /**
     * Test case for generateKepwDismantlePrintingPage
     *
     * Wydruk Karty Ewidencji Pojazdów Wycofanych z Eksploatacji ze stacji demontażu pojazdów.
     *
     */
    public function testGenerateKepwDismantlePrintingPage()
    {
    }

    /**
     * Test case for generateKezsPrintingPage
     *
     * Wydruk Karty Ewidencji Zużytego Sprzętu Elektrycznego i Elektronicznego.
     *
     */
    public function testGenerateKezsPrintingPage()
    {
    }

    /**
     * Test case for generateKpoConfirmation
     *
     * Wydruk potwierdzenia wystawienia dla Karty Przekazania Odpadów.
     *
     */
    public function testGenerateKpoConfirmation()
    {
    }

    /**
     * Test case for generateKpoPrintingPage
     *
     * Wydruk Karty Przekazania Odpadów.
     *
     */
    public function testGenerateKpoPrintingPage()
    {
    }

    /**
     * Test case for generateKpokConfirmation
     *
     * Wydruk potwierdzenia wystawienia dla Karty Przekazania Odpadów Komunalnych.
     *
     */
    public function testGenerateKpokConfirmation()
    {
    }

    /**
     * Test case for generateKpokReceivePrintingPage
     *
     * Wydruk Karty Przekazania Odpadów Komunalnych w trybie \"Odbiór\".
     *
     */
    public function testGenerateKpokReceivePrintingPage()
    {
    }

    /**
     * Test case for generateKpokTransferPrintingPage
     *
     * Wydruk Karty Przekazania Odpadów Komunalnych w trybie \"Przekazanie\".
     *
     */
    public function testGenerateKpokTransferPrintingPage()
    {
    }
}
