<?php
/**
 * WasteRegisterPublicApiApiModelsElasticsearchTerytCommuneEs
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * WasteRegisterPublicApiApiModelsElasticsearchTerytCommuneEs Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsElasticsearchTerytCommuneEs implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WasteRegisterPublic.Api.ApiModels.Elasticsearch.TerytCommuneEs';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'pk' => 'string',
        'fulltext' => 'string',
        'fulltext_html' => 'string',
        'rodzaj_gminy' => 'string',
        'gmina' => 'string',
        'powiat' => 'string',
        'wojewodztwo' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'pk' => null,
        'fulltext' => null,
        'fulltext_html' => null,
        'rodzaj_gminy' => null,
        'gmina' => null,
        'powiat' => null,
        'wojewodztwo' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'pk' => 'pk',
        'fulltext' => 'fulltext',
        'fulltext_html' => 'fulltext_html',
        'rodzaj_gminy' => 'rodzaj_gminy',
        'gmina' => 'gmina',
        'powiat' => 'powiat',
        'wojewodztwo' => 'wojewodztwo'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'pk' => 'setPk',
        'fulltext' => 'setFulltext',
        'fulltext_html' => 'setFulltextHtml',
        'rodzaj_gminy' => 'setRodzajGminy',
        'gmina' => 'setGmina',
        'powiat' => 'setPowiat',
        'wojewodztwo' => 'setWojewodztwo'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'pk' => 'getPk',
        'fulltext' => 'getFulltext',
        'fulltext_html' => 'getFulltextHtml',
        'rodzaj_gminy' => 'getRodzajGminy',
        'gmina' => 'getGmina',
        'powiat' => 'getPowiat',
        'wojewodztwo' => 'getWojewodztwo'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['pk'] = isset($data['pk']) ? $data['pk'] : null;
        $this->container['fulltext'] = isset($data['fulltext']) ? $data['fulltext'] : null;
        $this->container['fulltext_html'] = isset($data['fulltext_html']) ? $data['fulltext_html'] : null;
        $this->container['rodzaj_gminy'] = isset($data['rodzaj_gminy']) ? $data['rodzaj_gminy'] : null;
        $this->container['gmina'] = isset($data['gmina']) ? $data['gmina'] : null;
        $this->container['powiat'] = isset($data['powiat']) ? $data['powiat'] : null;
        $this->container['wojewodztwo'] = isset($data['wojewodztwo']) ? $data['wojewodztwo'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets pk
     *
     * @return string
     */
    public function getPk()
    {
        return $this->container['pk'];
    }

    /**
     * Sets pk
     *
     * @param string $pk pk
     *
     * @return $this
     */
    public function setPk($pk)
    {
        $this->container['pk'] = $pk;

        return $this;
    }

    /**
     * Gets fulltext
     *
     * @return string
     */
    public function getFulltext()
    {
        return $this->container['fulltext'];
    }

    /**
     * Sets fulltext
     *
     * @param string $fulltext fulltext
     *
     * @return $this
     */
    public function setFulltext($fulltext)
    {
        $this->container['fulltext'] = $fulltext;

        return $this;
    }

    /**
     * Gets fulltext_html
     *
     * @return string
     */
    public function getFulltextHtml()
    {
        return $this->container['fulltext_html'];
    }

    /**
     * Sets fulltext_html
     *
     * @param string $fulltext_html fulltext_html
     *
     * @return $this
     */
    public function setFulltextHtml($fulltext_html)
    {
        $this->container['fulltext_html'] = $fulltext_html;

        return $this;
    }

    /**
     * Gets rodzaj_gminy
     *
     * @return string
     */
    public function getRodzajGminy()
    {
        return $this->container['rodzaj_gminy'];
    }

    /**
     * Sets rodzaj_gminy
     *
     * @param string $rodzaj_gminy rodzaj_gminy
     *
     * @return $this
     */
    public function setRodzajGminy($rodzaj_gminy)
    {
        $this->container['rodzaj_gminy'] = $rodzaj_gminy;

        return $this;
    }

    /**
     * Gets gmina
     *
     * @return string
     */
    public function getGmina()
    {
        return $this->container['gmina'];
    }

    /**
     * Sets gmina
     *
     * @param string $gmina gmina
     *
     * @return $this
     */
    public function setGmina($gmina)
    {
        $this->container['gmina'] = $gmina;

        return $this;
    }

    /**
     * Gets powiat
     *
     * @return string
     */
    public function getPowiat()
    {
        return $this->container['powiat'];
    }

    /**
     * Sets powiat
     *
     * @param string $powiat powiat
     *
     * @return $this
     */
    public function setPowiat($powiat)
    {
        $this->container['powiat'] = $powiat;

        return $this;
    }

    /**
     * Gets wojewodztwo
     *
     * @return string
     */
    public function getWojewodztwo()
    {
        return $this->container['wojewodztwo'];
    }

    /**
     * Sets wojewodztwo
     *
     * @param string $wojewodztwo wojewodztwo
     *
     * @return $this
     */
    public function setWojewodztwo($wojewodztwo)
    {
        $this->container['wojewodztwo'] = $wojewodztwo;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


