<?php
/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1GetKekosPrintingPageResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WasteRegisterPublic.Api.ApiModels.Responses.WasteRegister.MunicipalSewageSludgeCard.V1.GetKekosPrintingPageResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'card_number' => 'string',
        'calendar_year' => 'string',
        'waste_code_with_description' => 'string',
        'company_name' => 'string',
        'company_adress' => 'string',
        'company_identification_number' => 'string',
        'company_nip' => 'string',
        'company_nip_eu' => 'string',
        'eup_name' => 'string',
        'eup_identification_number' => 'string',
        'eup_adress' => 'string',
        'sludge_mass_mg_sum' => 'double',
        'sludge_mass_mg_sm_sum' => 'double',
        'applied_sludge_mass_sum' => 'double',
        'applied_sludge_dry_matter_mass_sum' => 'double',
        'list_items' => '\Swagger\Client\Model\WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosPrintingPageListItem[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'card_number' => null,
        'calendar_year' => null,
        'waste_code_with_description' => null,
        'company_name' => null,
        'company_adress' => null,
        'company_identification_number' => null,
        'company_nip' => null,
        'company_nip_eu' => null,
        'eup_name' => null,
        'eup_identification_number' => null,
        'eup_adress' => null,
        'sludge_mass_mg_sum' => 'double',
        'sludge_mass_mg_sm_sum' => 'double',
        'applied_sludge_mass_sum' => 'double',
        'applied_sludge_dry_matter_mass_sum' => 'double',
        'list_items' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'card_number' => 'cardNumber',
        'calendar_year' => 'calendarYear',
        'waste_code_with_description' => 'wasteCodeWithDescription',
        'company_name' => 'companyName',
        'company_adress' => 'companyAdress',
        'company_identification_number' => 'companyIdentificationNumber',
        'company_nip' => 'companyNip',
        'company_nip_eu' => 'companyNipEu',
        'eup_name' => 'eupName',
        'eup_identification_number' => 'eupIdentificationNumber',
        'eup_adress' => 'eupAdress',
        'sludge_mass_mg_sum' => 'sludgeMassMgSum',
        'sludge_mass_mg_sm_sum' => 'sludgeMassMgSmSum',
        'applied_sludge_mass_sum' => 'appliedSludgeMassSum',
        'applied_sludge_dry_matter_mass_sum' => 'appliedSludgeDryMatterMassSum',
        'list_items' => 'listItems'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'card_number' => 'setCardNumber',
        'calendar_year' => 'setCalendarYear',
        'waste_code_with_description' => 'setWasteCodeWithDescription',
        'company_name' => 'setCompanyName',
        'company_adress' => 'setCompanyAdress',
        'company_identification_number' => 'setCompanyIdentificationNumber',
        'company_nip' => 'setCompanyNip',
        'company_nip_eu' => 'setCompanyNipEu',
        'eup_name' => 'setEupName',
        'eup_identification_number' => 'setEupIdentificationNumber',
        'eup_adress' => 'setEupAdress',
        'sludge_mass_mg_sum' => 'setSludgeMassMgSum',
        'sludge_mass_mg_sm_sum' => 'setSludgeMassMgSmSum',
        'applied_sludge_mass_sum' => 'setAppliedSludgeMassSum',
        'applied_sludge_dry_matter_mass_sum' => 'setAppliedSludgeDryMatterMassSum',
        'list_items' => 'setListItems'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'card_number' => 'getCardNumber',
        'calendar_year' => 'getCalendarYear',
        'waste_code_with_description' => 'getWasteCodeWithDescription',
        'company_name' => 'getCompanyName',
        'company_adress' => 'getCompanyAdress',
        'company_identification_number' => 'getCompanyIdentificationNumber',
        'company_nip' => 'getCompanyNip',
        'company_nip_eu' => 'getCompanyNipEu',
        'eup_name' => 'getEupName',
        'eup_identification_number' => 'getEupIdentificationNumber',
        'eup_adress' => 'getEupAdress',
        'sludge_mass_mg_sum' => 'getSludgeMassMgSum',
        'sludge_mass_mg_sm_sum' => 'getSludgeMassMgSmSum',
        'applied_sludge_mass_sum' => 'getAppliedSludgeMassSum',
        'applied_sludge_dry_matter_mass_sum' => 'getAppliedSludgeDryMatterMassSum',
        'list_items' => 'getListItems'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['card_number'] = isset($data['card_number']) ? $data['card_number'] : null;
        $this->container['calendar_year'] = isset($data['calendar_year']) ? $data['calendar_year'] : null;
        $this->container['waste_code_with_description'] = isset($data['waste_code_with_description']) ? $data['waste_code_with_description'] : null;
        $this->container['company_name'] = isset($data['company_name']) ? $data['company_name'] : null;
        $this->container['company_adress'] = isset($data['company_adress']) ? $data['company_adress'] : null;
        $this->container['company_identification_number'] = isset($data['company_identification_number']) ? $data['company_identification_number'] : null;
        $this->container['company_nip'] = isset($data['company_nip']) ? $data['company_nip'] : null;
        $this->container['company_nip_eu'] = isset($data['company_nip_eu']) ? $data['company_nip_eu'] : null;
        $this->container['eup_name'] = isset($data['eup_name']) ? $data['eup_name'] : null;
        $this->container['eup_identification_number'] = isset($data['eup_identification_number']) ? $data['eup_identification_number'] : null;
        $this->container['eup_adress'] = isset($data['eup_adress']) ? $data['eup_adress'] : null;
        $this->container['sludge_mass_mg_sum'] = isset($data['sludge_mass_mg_sum']) ? $data['sludge_mass_mg_sum'] : null;
        $this->container['sludge_mass_mg_sm_sum'] = isset($data['sludge_mass_mg_sm_sum']) ? $data['sludge_mass_mg_sm_sum'] : null;
        $this->container['applied_sludge_mass_sum'] = isset($data['applied_sludge_mass_sum']) ? $data['applied_sludge_mass_sum'] : null;
        $this->container['applied_sludge_dry_matter_mass_sum'] = isset($data['applied_sludge_dry_matter_mass_sum']) ? $data['applied_sludge_dry_matter_mass_sum'] : null;
        $this->container['list_items'] = isset($data['list_items']) ? $data['list_items'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets card_number
     *
     * @return string
     */
    public function getCardNumber()
    {
        return $this->container['card_number'];
    }

    /**
     * Sets card_number
     *
     * @param string $card_number Numer karty
     *
     * @return $this
     */
    public function setCardNumber($card_number)
    {
        $this->container['card_number'] = $card_number;

        return $this;
    }

    /**
     * Gets calendar_year
     *
     * @return string
     */
    public function getCalendarYear()
    {
        return $this->container['calendar_year'];
    }

    /**
     * Sets calendar_year
     *
     * @param string $calendar_year Rok kalendarzowy
     *
     * @return $this
     */
    public function setCalendarYear($calendar_year)
    {
        $this->container['calendar_year'] = $calendar_year;

        return $this;
    }

    /**
     * Gets waste_code_with_description
     *
     * @return string
     */
    public function getWasteCodeWithDescription()
    {
        return $this->container['waste_code_with_description'];
    }

    /**
     * Sets waste_code_with_description
     *
     * @param string $waste_code_with_description 
     *
     * @return $this
     */
    public function setWasteCodeWithDescription($waste_code_with_description)
    {
        $this->container['waste_code_with_description'] = $waste_code_with_description;

        return $this;
    }

    /**
     * Gets company_name
     *
     * @return string
     */
    public function getCompanyName()
    {
        return $this->container['company_name'];
    }

    /**
     * Sets company_name
     *
     * @param string $company_name Nazwa lub imię i nazwisko
     *
     * @return $this
     */
    public function setCompanyName($company_name)
    {
        $this->container['company_name'] = $company_name;

        return $this;
    }

    /**
     * Gets company_adress
     *
     * @return string
     */
    public function getCompanyAdress()
    {
        return $this->container['company_adress'];
    }

    /**
     * Sets company_adress
     *
     * @param string $company_adress Adres
     *
     * @return $this
     */
    public function setCompanyAdress($company_adress)
    {
        $this->container['company_adress'] = $company_adress;

        return $this;
    }

    /**
     * Gets company_identification_number
     *
     * @return string
     */
    public function getCompanyIdentificationNumber()
    {
        return $this->container['company_identification_number'];
    }

    /**
     * Sets company_identification_number
     *
     * @param string $company_identification_number Numer rejestrowy
     *
     * @return $this
     */
    public function setCompanyIdentificationNumber($company_identification_number)
    {
        $this->container['company_identification_number'] = $company_identification_number;

        return $this;
    }

    /**
     * Gets company_nip
     *
     * @return string
     */
    public function getCompanyNip()
    {
        return $this->container['company_nip'];
    }

    /**
     * Sets company_nip
     *
     * @param string $company_nip NIP
     *
     * @return $this
     */
    public function setCompanyNip($company_nip)
    {
        $this->container['company_nip'] = $company_nip;

        return $this;
    }

    /**
     * Gets company_nip_eu
     *
     * @return string
     */
    public function getCompanyNipEu()
    {
        return $this->container['company_nip_eu'];
    }

    /**
     * Sets company_nip_eu
     *
     * @param string $company_nip_eu NIP europejski
     *
     * @return $this
     */
    public function setCompanyNipEu($company_nip_eu)
    {
        $this->container['company_nip_eu'] = $company_nip_eu;

        return $this;
    }

    /**
     * Gets eup_name
     *
     * @return string
     */
    public function getEupName()
    {
        return $this->container['eup_name'];
    }

    /**
     * Sets eup_name
     *
     * @param string $eup_name Nazwa miejsca prowadzenia działalności
     *
     * @return $this
     */
    public function setEupName($eup_name)
    {
        $this->container['eup_name'] = $eup_name;

        return $this;
    }

    /**
     * Gets eup_identification_number
     *
     * @return string
     */
    public function getEupIdentificationNumber()
    {
        return $this->container['eup_identification_number'];
    }

    /**
     * Sets eup_identification_number
     *
     * @param string $eup_identification_number Numer miejsca prowadzenia działalności
     *
     * @return $this
     */
    public function setEupIdentificationNumber($eup_identification_number)
    {
        $this->container['eup_identification_number'] = $eup_identification_number;

        return $this;
    }

    /**
     * Gets eup_adress
     *
     * @return string
     */
    public function getEupAdress()
    {
        return $this->container['eup_adress'];
    }

    /**
     * Sets eup_adress
     *
     * @param string $eup_adress Adres miejsca prowadzenia działalności
     *
     * @return $this
     */
    public function setEupAdress($eup_adress)
    {
        $this->container['eup_adress'] = $eup_adress;

        return $this;
    }

    /**
     * Gets sludge_mass_mg_sum
     *
     * @return double
     */
    public function getSludgeMassMgSum()
    {
        return $this->container['sludge_mass_mg_sum'];
    }

    /**
     * Sets sludge_mass_mg_sum
     *
     * @param double $sludge_mass_mg_sum 
     *
     * @return $this
     */
    public function setSludgeMassMgSum($sludge_mass_mg_sum)
    {
        $this->container['sludge_mass_mg_sum'] = $sludge_mass_mg_sum;

        return $this;
    }

    /**
     * Gets sludge_mass_mg_sm_sum
     *
     * @return double
     */
    public function getSludgeMassMgSmSum()
    {
        return $this->container['sludge_mass_mg_sm_sum'];
    }

    /**
     * Sets sludge_mass_mg_sm_sum
     *
     * @param double $sludge_mass_mg_sm_sum 
     *
     * @return $this
     */
    public function setSludgeMassMgSmSum($sludge_mass_mg_sm_sum)
    {
        $this->container['sludge_mass_mg_sm_sum'] = $sludge_mass_mg_sm_sum;

        return $this;
    }

    /**
     * Gets applied_sludge_mass_sum
     *
     * @return double
     */
    public function getAppliedSludgeMassSum()
    {
        return $this->container['applied_sludge_mass_sum'];
    }

    /**
     * Sets applied_sludge_mass_sum
     *
     * @param double $applied_sludge_mass_sum 
     *
     * @return $this
     */
    public function setAppliedSludgeMassSum($applied_sludge_mass_sum)
    {
        $this->container['applied_sludge_mass_sum'] = $applied_sludge_mass_sum;

        return $this;
    }

    /**
     * Gets applied_sludge_dry_matter_mass_sum
     *
     * @return double
     */
    public function getAppliedSludgeDryMatterMassSum()
    {
        return $this->container['applied_sludge_dry_matter_mass_sum'];
    }

    /**
     * Sets applied_sludge_dry_matter_mass_sum
     *
     * @param double $applied_sludge_dry_matter_mass_sum 
     *
     * @return $this
     */
    public function setAppliedSludgeDryMatterMassSum($applied_sludge_dry_matter_mass_sum)
    {
        $this->container['applied_sludge_dry_matter_mass_sum'] = $applied_sludge_dry_matter_mass_sum;

        return $this;
    }

    /**
     * Gets list_items
     *
     * @return \Swagger\Client\Model\WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosPrintingPageListItem[]
     */
    public function getListItems()
    {
        return $this->container['list_items'];
    }

    /**
     * Sets list_items
     *
     * @param \Swagger\Client\Model\WasteRegisterPublicApiApiModelsResponsesWasteRegisterMunicipalSewageSludgeCardV1KekosPrintingPageListItem[] $list_items 
     *
     * @return $this
     */
    public function setListItems($list_items)
    {
        $this->container['list_items'] = $list_items;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


