<?php
/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetCollectingTransferredVehiclesResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetCollectingTransferredVehiclesResponse Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetCollectingTransferredVehiclesResponse implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'WasteRegisterPublic.Api.ApiModels.Responses.WasteRegister.WreckWasteRecordCard.V1.GetCollectingTransferredVehiclesResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'year' => 'int',
        'waste_code' => 'string',
        'vehicles_mass_summary' => 'double',
        'vehicles_count_summary' => 'int',
        'card_number' => 'string',
        'initial_vehicles_mass' => 'double',
        'initial_vehicles_count' => 'int',
        'waste_code_extended' => 'bool',
        'waste_code_extended_description' => 'string',
        'hazardous_waste_reclassification' => 'bool',
        'hazardous_waste_reclassification_description' => 'string',
        'collecting_transferred_vehicles' => '\Swagger\Client\Model\WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1PaginatedPageCollectingTransferredVehicleListItem'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'year' => 'int32',
        'waste_code' => null,
        'vehicles_mass_summary' => 'double',
        'vehicles_count_summary' => 'int32',
        'card_number' => null,
        'initial_vehicles_mass' => 'double',
        'initial_vehicles_count' => 'int32',
        'waste_code_extended' => null,
        'waste_code_extended_description' => null,
        'hazardous_waste_reclassification' => null,
        'hazardous_waste_reclassification_description' => null,
        'collecting_transferred_vehicles' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'year' => 'year',
        'waste_code' => 'wasteCode',
        'vehicles_mass_summary' => 'vehiclesMassSummary',
        'vehicles_count_summary' => 'vehiclesCountSummary',
        'card_number' => 'cardNumber',
        'initial_vehicles_mass' => 'initialVehiclesMass',
        'initial_vehicles_count' => 'initialVehiclesCount',
        'waste_code_extended' => 'wasteCodeExtended',
        'waste_code_extended_description' => 'wasteCodeExtendedDescription',
        'hazardous_waste_reclassification' => 'hazardousWasteReclassification',
        'hazardous_waste_reclassification_description' => 'hazardousWasteReclassificationDescription',
        'collecting_transferred_vehicles' => 'collectingTransferredVehicles'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'year' => 'setYear',
        'waste_code' => 'setWasteCode',
        'vehicles_mass_summary' => 'setVehiclesMassSummary',
        'vehicles_count_summary' => 'setVehiclesCountSummary',
        'card_number' => 'setCardNumber',
        'initial_vehicles_mass' => 'setInitialVehiclesMass',
        'initial_vehicles_count' => 'setInitialVehiclesCount',
        'waste_code_extended' => 'setWasteCodeExtended',
        'waste_code_extended_description' => 'setWasteCodeExtendedDescription',
        'hazardous_waste_reclassification' => 'setHazardousWasteReclassification',
        'hazardous_waste_reclassification_description' => 'setHazardousWasteReclassificationDescription',
        'collecting_transferred_vehicles' => 'setCollectingTransferredVehicles'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'year' => 'getYear',
        'waste_code' => 'getWasteCode',
        'vehicles_mass_summary' => 'getVehiclesMassSummary',
        'vehicles_count_summary' => 'getVehiclesCountSummary',
        'card_number' => 'getCardNumber',
        'initial_vehicles_mass' => 'getInitialVehiclesMass',
        'initial_vehicles_count' => 'getInitialVehiclesCount',
        'waste_code_extended' => 'getWasteCodeExtended',
        'waste_code_extended_description' => 'getWasteCodeExtendedDescription',
        'hazardous_waste_reclassification' => 'getHazardousWasteReclassification',
        'hazardous_waste_reclassification_description' => 'getHazardousWasteReclassificationDescription',
        'collecting_transferred_vehicles' => 'getCollectingTransferredVehicles'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['year'] = isset($data['year']) ? $data['year'] : null;
        $this->container['waste_code'] = isset($data['waste_code']) ? $data['waste_code'] : null;
        $this->container['vehicles_mass_summary'] = isset($data['vehicles_mass_summary']) ? $data['vehicles_mass_summary'] : null;
        $this->container['vehicles_count_summary'] = isset($data['vehicles_count_summary']) ? $data['vehicles_count_summary'] : null;
        $this->container['card_number'] = isset($data['card_number']) ? $data['card_number'] : null;
        $this->container['initial_vehicles_mass'] = isset($data['initial_vehicles_mass']) ? $data['initial_vehicles_mass'] : null;
        $this->container['initial_vehicles_count'] = isset($data['initial_vehicles_count']) ? $data['initial_vehicles_count'] : null;
        $this->container['waste_code_extended'] = isset($data['waste_code_extended']) ? $data['waste_code_extended'] : null;
        $this->container['waste_code_extended_description'] = isset($data['waste_code_extended_description']) ? $data['waste_code_extended_description'] : null;
        $this->container['hazardous_waste_reclassification'] = isset($data['hazardous_waste_reclassification']) ? $data['hazardous_waste_reclassification'] : null;
        $this->container['hazardous_waste_reclassification_description'] = isset($data['hazardous_waste_reclassification_description']) ? $data['hazardous_waste_reclassification_description'] : null;
        $this->container['collecting_transferred_vehicles'] = isset($data['collecting_transferred_vehicles']) ? $data['collecting_transferred_vehicles'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets year
     *
     * @return int
     */
    public function getYear()
    {
        return $this->container['year'];
    }

    /**
     * Sets year
     *
     * @param int $year Rok kalendarzowy
     *
     * @return $this
     */
    public function setYear($year)
    {
        $this->container['year'] = $year;

        return $this;
    }

    /**
     * Gets waste_code
     *
     * @return string
     */
    public function getWasteCode()
    {
        return $this->container['waste_code'];
    }

    /**
     * Sets waste_code
     *
     * @param string $waste_code Kod odpadu
     *
     * @return $this
     */
    public function setWasteCode($waste_code)
    {
        $this->container['waste_code'] = $waste_code;

        return $this;
    }

    /**
     * Gets vehicles_mass_summary
     *
     * @return double
     */
    public function getVehiclesMassSummary()
    {
        return $this->container['vehicles_mass_summary'];
    }

    /**
     * Sets vehicles_mass_summary
     *
     * @param double $vehicles_mass_summary Łączna masa przyjętych pojazdów [Mg]
     *
     * @return $this
     */
    public function setVehiclesMassSummary($vehicles_mass_summary)
    {
        $this->container['vehicles_mass_summary'] = $vehicles_mass_summary;

        return $this;
    }

    /**
     * Gets vehicles_count_summary
     *
     * @return int
     */
    public function getVehiclesCountSummary()
    {
        return $this->container['vehicles_count_summary'];
    }

    /**
     * Sets vehicles_count_summary
     *
     * @param int $vehicles_count_summary Łączna liczba przyjętych pojazdów [szt.]
     *
     * @return $this
     */
    public function setVehiclesCountSummary($vehicles_count_summary)
    {
        $this->container['vehicles_count_summary'] = $vehicles_count_summary;

        return $this;
    }

    /**
     * Gets card_number
     *
     * @return string
     */
    public function getCardNumber()
    {
        return $this->container['card_number'];
    }

    /**
     * Sets card_number
     *
     * @param string $card_number Numer karty
     *
     * @return $this
     */
    public function setCardNumber($card_number)
    {
        $this->container['card_number'] = $card_number;

        return $this;
    }

    /**
     * Gets initial_vehicles_mass
     *
     * @return double
     */
    public function getInitialVehiclesMass()
    {
        return $this->container['initial_vehicles_mass'];
    }

    /**
     * Sets initial_vehicles_mass
     *
     * @param double $initial_vehicles_mass Masa pojazdów [Mg]
     *
     * @return $this
     */
    public function setInitialVehiclesMass($initial_vehicles_mass)
    {
        $this->container['initial_vehicles_mass'] = $initial_vehicles_mass;

        return $this;
    }

    /**
     * Gets initial_vehicles_count
     *
     * @return int
     */
    public function getInitialVehiclesCount()
    {
        return $this->container['initial_vehicles_count'];
    }

    /**
     * Sets initial_vehicles_count
     *
     * @param int $initial_vehicles_count Liczba pojazdów [szt.]
     *
     * @return $this
     */
    public function setInitialVehiclesCount($initial_vehicles_count)
    {
        $this->container['initial_vehicles_count'] = $initial_vehicles_count;

        return $this;
    }

    /**
     * Gets waste_code_extended
     *
     * @return bool
     */
    public function getWasteCodeExtended()
    {
        return $this->container['waste_code_extended'];
    }

    /**
     * Sets waste_code_extended
     *
     * @param bool $waste_code_extended Kod ex
     *
     * @return $this
     */
    public function setWasteCodeExtended($waste_code_extended)
    {
        $this->container['waste_code_extended'] = $waste_code_extended;

        return $this;
    }

    /**
     * Gets waste_code_extended_description
     *
     * @return string
     */
    public function getWasteCodeExtendedDescription()
    {
        return $this->container['waste_code_extended_description'];
    }

    /**
     * Sets waste_code_extended_description
     *
     * @param string $waste_code_extended_description Rodzaj odpadu ex
     *
     * @return $this
     */
    public function setWasteCodeExtendedDescription($waste_code_extended_description)
    {
        $this->container['waste_code_extended_description'] = $waste_code_extended_description;

        return $this;
    }

    /**
     * Gets hazardous_waste_reclassification
     *
     * @return bool
     */
    public function getHazardousWasteReclassification()
    {
        return $this->container['hazardous_waste_reclassification'];
    }

    /**
     * Sets hazardous_waste_reclassification
     *
     * @param bool $hazardous_waste_reclassification Zmiana statusu odpadów niebezpiecznych na odpady inne niż niebezpieczne
     *
     * @return $this
     */
    public function setHazardousWasteReclassification($hazardous_waste_reclassification)
    {
        $this->container['hazardous_waste_reclassification'] = $hazardous_waste_reclassification;

        return $this;
    }

    /**
     * Gets hazardous_waste_reclassification_description
     *
     * @return string
     */
    public function getHazardousWasteReclassificationDescription()
    {
        return $this->container['hazardous_waste_reclassification_description'];
    }

    /**
     * Sets hazardous_waste_reclassification_description
     *
     * @param string $hazardous_waste_reclassification_description Rodzaj odpadu
     *
     * @return $this
     */
    public function setHazardousWasteReclassificationDescription($hazardous_waste_reclassification_description)
    {
        $this->container['hazardous_waste_reclassification_description'] = $hazardous_waste_reclassification_description;

        return $this;
    }

    /**
     * Gets collecting_transferred_vehicles
     *
     * @return \Swagger\Client\Model\WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1PaginatedPageCollectingTransferredVehicleListItem
     */
    public function getCollectingTransferredVehicles()
    {
        return $this->container['collecting_transferred_vehicles'];
    }

    /**
     * Sets collecting_transferred_vehicles
     *
     * @param \Swagger\Client\Model\WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1PaginatedPageCollectingTransferredVehicleListItem $collecting_transferred_vehicles 
     *
     * @return $this
     */
    public function setCollectingTransferredVehicles($collecting_transferred_vehicles)
    {
        $this->container['collecting_transferred_vehicles'] = $collecting_transferred_vehicles;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


