<?php
/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardKeoGeneratedV1CreateKeoGeneratedRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardKeoGeneratedV1CreateKeoGeneratedRequestTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardKeoGeneratedV1CreateKeoGeneratedRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardKeoGeneratedV1CreateKeoGeneratedRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardKeoGeneratedV1CreateKeoGeneratedRequest"
     */
    public function testWasteRegisterPublicApiApiModelsRequestsWasteRegisterWasteRecordCardKeoGeneratedV1CreateKeoGeneratedRequest()
    {
    }

    /**
     * Test attribute "keo_id"
     */
    public function testPropertyKeoId()
    {
    }

    /**
     * Test attribute "installation_name"
     */
    public function testPropertyInstallationName()
    {
    }

    /**
     * Test attribute "waste_mass_installation"
     */
    public function testPropertyWasteMassInstallation()
    {
    }

    /**
     * Test attribute "waste_mass_excluding_installation"
     */
    public function testPropertyWasteMassExcludingInstallation()
    {
    }

    /**
     * Test attribute "waste_from_services"
     */
    public function testPropertyWasteFromServices()
    {
    }

    /**
     * Test attribute "commune_id"
     */
    public function testPropertyCommuneId()
    {
    }

    /**
     * Test attribute "manufacture_date"
     */
    public function testPropertyManufactureDate()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification"
     */
    public function testPropertyHazardousWasteReclassification()
    {
    }
}
