<?php
/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiverKpoAsSenderListItemDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiverKpoAsSenderListItemDtoTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiverKpoAsSenderListItemDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiverKpoAsSenderListItemDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiverKpoAsSenderListItemDto"
     */
    public function testWasteRegisterPublicApiApiModelsResponsesWasteRegisterWasteTransferCardV1ReceiverKpoAsSenderListItemDto()
    {
    }

    /**
     * Test attribute "kpo_id"
     */
    public function testPropertyKpoId()
    {
    }

    /**
     * Test attribute "receiver_identification_number"
     */
    public function testPropertyReceiverIdentificationNumber()
    {
    }

    /**
     * Test attribute "receiver_company_name"
     */
    public function testPropertyReceiverCompanyName()
    {
    }

    /**
     * Test attribute "receiver_nip"
     */
    public function testPropertyReceiverNip()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "receive_confirmation_time"
     */
    public function testPropertyReceiveConfirmationTime()
    {
    }

    /**
     * Test attribute "address_html"
     */
    public function testPropertyAddressHtml()
    {
    }

    /**
     * Test attribute "teryt_pk"
     */
    public function testPropertyTerytPk()
    {
    }

    /**
     * Test attribute "building_number"
     */
    public function testPropertyBuildingNumber()
    {
    }

    /**
     * Test attribute "local_number"
     */
    public function testPropertyLocalNumber()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "has_no_building_number"
     */
    public function testPropertyHasNoBuildingNumber()
    {
    }

    /**
     * Test attribute "foreign_company"
     */
    public function testPropertyForeignCompany()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "country_name"
     */
    public function testPropertyCountryName()
    {
    }

    /**
     * Test attribute "locality"
     */
    public function testPropertyLocality()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "waste_mass"
     */
    public function testPropertyWasteMass()
    {
    }

    /**
     * Test attribute "is_used"
     */
    public function testPropertyIsUsed()
    {
    }

    /**
     * Test attribute "waste_code"
     */
    public function testPropertyWasteCode()
    {
    }

    /**
     * Test attribute "waste_code_description"
     */
    public function testPropertyWasteCodeDescription()
    {
    }

    /**
     * Test attribute "waste_code_extended"
     */
    public function testPropertyWasteCodeExtended()
    {
    }

    /**
     * Test attribute "waste_code_extended_description"
     */
    public function testPropertyWasteCodeExtendedDescription()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification"
     */
    public function testPropertyHazardousWasteReclassification()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification_description"
     */
    public function testPropertyHazardousWasteReclassificationDescription()
    {
    }

    /**
     * Test attribute "is_waste_generating"
     */
    public function testPropertyIsWasteGenerating()
    {
    }

    /**
     * Test attribute "waste_generated_teryt"
     */
    public function testPropertyWasteGeneratedTeryt()
    {
    }

    /**
     * Test attribute "waste_generating_additional_info"
     */
    public function testPropertyWasteGeneratingAdditionalInfo()
    {
    }

    /**
     * Test attribute "waste_generated_teryt_pk"
     */
    public function testPropertyWasteGeneratedTerytPk()
    {
    }
}
