<?php
/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProcessedWasteResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProcessedWasteResponseTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProcessedWasteResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProcessedWasteResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProcessedWasteResponse"
     */
    public function testWasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1GetDismantleProcessedWasteResponse()
    {
    }

    /**
     * Test attribute "kepw_dismantle_processed_waste_id"
     */
    public function testPropertyKepwDismantleProcessedWasteId()
    {
    }

    /**
     * Test attribute "kepw_id"
     */
    public function testPropertyKepwId()
    {
    }

    /**
     * Test attribute "waste_code_id"
     */
    public function testPropertyWasteCodeId()
    {
    }

    /**
     * Test attribute "waste_code"
     */
    public function testPropertyWasteCode()
    {
    }

    /**
     * Test attribute "recycled_waste_mass"
     */
    public function testPropertyRecycledWasteMass()
    {
    }

    /**
     * Test attribute "energy_recovery_waste_mass"
     */
    public function testPropertyEnergyRecoveryWasteMass()
    {
    }

    /**
     * Test attribute "other_than_recycling_waste_mass"
     */
    public function testPropertyOtherThanRecyclingWasteMass()
    {
    }

    /**
     * Test attribute "waste_code_extended"
     */
    public function testPropertyWasteCodeExtended()
    {
    }

    /**
     * Test attribute "waste_code_extended_description"
     */
    public function testPropertyWasteCodeExtendedDescription()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification"
     */
    public function testPropertyHazardousWasteReclassification()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification_description"
     */
    public function testPropertyHazardousWasteReclassificationDescription()
    {
    }

    /**
     * Test attribute "installation_name"
     */
    public function testPropertyInstallationName()
    {
    }
}
