<?php
/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1KpokTransferPrintingPageTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1KpokTransferPrintingPageTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1KpokTransferPrintingPage
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1KpokTransferPrintingPageTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1KpokTransferPrintingPage"
     */
    public function testWasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteTransferCardV1KpokTransferPrintingPage()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "card_status"
     */
    public function testPropertyCardStatus()
    {
    }

    /**
     * Test attribute "calendar_year"
     */
    public function testPropertyCalendarYear()
    {
    }

    /**
     * Test attribute "sender_name_or_first_name_and_last_name"
     */
    public function testPropertySenderNameOrFirstNameAndLastName()
    {
    }

    /**
     * Test attribute "sender_address"
     */
    public function testPropertySenderAddress()
    {
    }

    /**
     * Test attribute "sender_eup_number"
     */
    public function testPropertySenderEupNumber()
    {
    }

    /**
     * Test attribute "sender_eup_name"
     */
    public function testPropertySenderEupName()
    {
    }

    /**
     * Test attribute "sender_eup_address"
     */
    public function testPropertySenderEupAddress()
    {
    }

    /**
     * Test attribute "sender_identification_number"
     */
    public function testPropertySenderIdentificationNumber()
    {
    }

    /**
     * Test attribute "sender_nip"
     */
    public function testPropertySenderNip()
    {
    }

    /**
     * Test attribute "sender_nip_eu"
     */
    public function testPropertySenderNipEu()
    {
    }

    /**
     * Test attribute "carrier_name_or_first_name_and_last_name"
     */
    public function testPropertyCarrierNameOrFirstNameAndLastName()
    {
    }

    /**
     * Test attribute "carrier_address"
     */
    public function testPropertyCarrierAddress()
    {
    }

    /**
     * Test attribute "carrier_identification_number"
     */
    public function testPropertyCarrierIdentificationNumber()
    {
    }

    /**
     * Test attribute "carrier_nip"
     */
    public function testPropertyCarrierNip()
    {
    }

    /**
     * Test attribute "carrier_nip_eu"
     */
    public function testPropertyCarrierNipEu()
    {
    }

    /**
     * Test attribute "receiver_name_or_first_name_and_last_name"
     */
    public function testPropertyReceiverNameOrFirstNameAndLastName()
    {
    }

    /**
     * Test attribute "receiver_address"
     */
    public function testPropertyReceiverAddress()
    {
    }

    /**
     * Test attribute "receiver_eup_number"
     */
    public function testPropertyReceiverEupNumber()
    {
    }

    /**
     * Test attribute "receiver_eup_name"
     */
    public function testPropertyReceiverEupName()
    {
    }

    /**
     * Test attribute "receiver_eup_address"
     */
    public function testPropertyReceiverEupAddress()
    {
    }

    /**
     * Test attribute "receiver_identification_number"
     */
    public function testPropertyReceiverIdentificationNumber()
    {
    }

    /**
     * Test attribute "receiver_nip"
     */
    public function testPropertyReceiverNip()
    {
    }

    /**
     * Test attribute "receiver_nip_eu"
     */
    public function testPropertyReceiverNipEu()
    {
    }

    /**
     * Test attribute "commune_name"
     */
    public function testPropertyCommuneName()
    {
    }

    /**
     * Test attribute "commune_area"
     */
    public function testPropertyCommuneArea()
    {
    }

    /**
     * Test attribute "waste_code_and_description"
     */
    public function testPropertyWasteCodeAndDescription()
    {
    }

    /**
     * Test attribute "waste_mass"
     */
    public function testPropertyWasteMass()
    {
    }

    /**
     * Test attribute "remarks"
     */
    public function testPropertyRemarks()
    {
    }

    /**
     * Test attribute "vehicle_reg_number"
     */
    public function testPropertyVehicleRegNumber()
    {
    }

    /**
     * Test attribute "real_transport_date"
     */
    public function testPropertyRealTransportDate()
    {
    }

    /**
     * Test attribute "real_transport_time"
     */
    public function testPropertyRealTransportTime()
    {
    }

    /**
     * Test attribute "receive_confirmation_date"
     */
    public function testPropertyReceiveConfirmationDate()
    {
    }

    /**
     * Test attribute "receive_confirmation_time"
     */
    public function testPropertyReceiveConfirmationTime()
    {
    }

    /**
     * Test attribute "approval_date"
     */
    public function testPropertyApprovalDate()
    {
    }

    /**
     * Test attribute "approval_time"
     */
    public function testPropertyApprovalTime()
    {
    }

    /**
     * Test attribute "approved_by_user"
     */
    public function testPropertyApprovedByUser()
    {
    }

    /**
     * Test attribute "transport_confirmation_date"
     */
    public function testPropertyTransportConfirmationDate()
    {
    }

    /**
     * Test attribute "transport_confirmation_time"
     */
    public function testPropertyTransportConfirmationTime()
    {
    }

    /**
     * Test attribute "transport_confirmed_by_user"
     */
    public function testPropertyTransportConfirmedByUser()
    {
    }

    /**
     * Test attribute "receive_confirmed_by_user"
     */
    public function testPropertyReceiveConfirmedByUser()
    {
    }

    /**
     * Test attribute "waste_code_extended"
     */
    public function testPropertyWasteCodeExtended()
    {
    }

    /**
     * Test attribute "waste_code_extended_description"
     */
    public function testPropertyWasteCodeExtendedDescription()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification"
     */
    public function testPropertyHazardousWasteReclassification()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification_description"
     */
    public function testPropertyHazardousWasteReclassificationDescription()
    {
    }

    /**
     * Test attribute "additional_info"
     */
    public function testPropertyAdditionalInfo()
    {
    }
}
