<?php
/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchSenderKpokAsReceiverRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchSenderKpokAsReceiverRequestTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchSenderKpokAsReceiverRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchSenderKpokAsReceiverRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchSenderKpokAsReceiverRequest"
     */
    public function testWasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteTransferCardSearchCardsV1SearchSenderKpokAsReceiverRequest()
    {
    }

    /**
     * Test attribute "page_size"
     */
    public function testPropertyPageSize()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "sender_nip"
     */
    public function testPropertySenderNip()
    {
    }

    /**
     * Test attribute "sender_identification_number"
     */
    public function testPropertySenderIdentificationNumber()
    {
    }

    /**
     * Test attribute "sender_name"
     */
    public function testPropertySenderName()
    {
    }

    /**
     * Test attribute "receive_confirmation_time"
     */
    public function testPropertyReceiveConfirmationTime()
    {
    }

    /**
     * Test attribute "card_status_code_names"
     */
    public function testPropertyCardStatusCodeNames()
    {
    }

    /**
     * Test attribute "waste_code_name"
     */
    public function testPropertyWasteCodeName()
    {
    }

    /**
     * Test attribute "pagination_parameters"
     */
    public function testPropertyPaginationParameters()
    {
    }

    /**
     * Test attribute "is_used"
     */
    public function testPropertyIsUsed()
    {
    }

    /**
     * Test attribute "commune_id"
     */
    public function testPropertyCommuneId()
    {
    }
}
