<?php
/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequestTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest"
     */
    public function testWasteRegisterPublicApiApiModelsRequestsWasteRegisterMunicipalWasteRecordCardKeokReceivedV1CreateKeokReceivedRequest()
    {
    }

    /**
     * Test attribute "keok_id"
     */
    public function testPropertyKeokId()
    {
    }

    /**
     * Test attribute "kpok_id"
     */
    public function testPropertyKpokId()
    {
    }

    /**
     * Test attribute "received_with_kpok"
     */
    public function testPropertyReceivedWithKpok()
    {
    }

    /**
     * Test attribute "received_waste_mass"
     */
    public function testPropertyReceivedWasteMass()
    {
    }

    /**
     * Test attribute "receive_date"
     */
    public function testPropertyReceiveDate()
    {
    }

    /**
     * Test attribute "additional_info"
     */
    public function testPropertyAdditionalInfo()
    {
    }

    /**
     * Test attribute "installation_name"
     */
    public function testPropertyInstallationName()
    {
    }
}
