<?php
/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterElectronicWasteRecordCardV1KezsEquipmentGroupCardDtoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterElectronicWasteRecordCardV1KezsEquipmentGroupCardDtoTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsResponsesWasteRegisterElectronicWasteRecordCardV1KezsEquipmentGroupCardDto
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsResponsesWasteRegisterElectronicWasteRecordCardV1KezsEquipmentGroupCardDtoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsResponsesWasteRegisterElectronicWasteRecordCardV1KezsEquipmentGroupCardDto"
     */
    public function testWasteRegisterPublicApiApiModelsResponsesWasteRegisterElectronicWasteRecordCardV1KezsEquipmentGroupCardDto()
    {
    }

    /**
     * Test attribute "kezs_equipment_group_card_id"
     */
    public function testPropertyKezsEquipmentGroupCardId()
    {
    }

    /**
     * Test attribute "kezs_equipment_group_id"
     */
    public function testPropertyKezsEquipmentGroupId()
    {
    }

    /**
     * Test attribute "kezs_id"
     */
    public function testPropertyKezsId()
    {
    }

    /**
     * Test attribute "stock_mass"
     */
    public function testPropertyStockMass()
    {
    }

    /**
     * Test attribute "kezs_equipment_group"
     */
    public function testPropertyKezsEquipmentGroup()
    {
    }

    /**
     * Test attribute "kezs_stock_waste_mass_group"
     */
    public function testPropertyKezsStockWasteMassGroup()
    {
    }

    /**
     * Test attribute "kezs_equipment_collecting_entry"
     */
    public function testPropertyKezsEquipmentCollectingEntry()
    {
    }

    /**
     * Test attribute "kezs_equipment_management"
     */
    public function testPropertyKezsEquipmentManagement()
    {
    }

    /**
     * Test attribute "kezs_waste_management_handed_over"
     */
    public function testPropertyKezsWasteManagementHandedOver()
    {
    }

    /**
     * Test attribute "kezs_waste_management_on_ones_own"
     */
    public function testPropertyKezsWasteManagementOnOnesOwn()
    {
    }

    /**
     * Test attribute "kezs_used_equipment_waste_generation"
     */
    public function testPropertyKezsUsedEquipmentWasteGeneration()
    {
    }

    /**
     * Test attribute "kezs_equipment_group_code_name"
     */
    public function testPropertyKezsEquipmentGroupCodeName()
    {
    }
}
