<?php
/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CollectingTransferredVehicleListItemTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CollectingTransferredVehicleListItemTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CollectingTransferredVehicleListItem
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CollectingTransferredVehicleListItemTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CollectingTransferredVehicleListItem"
     */
    public function testWasteRegisterPublicApiApiModelsResponsesWasteRegisterWreckWasteRecordCardV1CollectingTransferredVehicleListItem()
    {
    }

    /**
     * Test attribute "collecting_transferred_vehicles_id"
     */
    public function testPropertyCollectingTransferredVehiclesId()
    {
    }

    /**
     * Test attribute "transfer_date"
     */
    public function testPropertyTransferDate()
    {
    }

    /**
     * Test attribute "vehicles_mass"
     */
    public function testPropertyVehiclesMass()
    {
    }

    /**
     * Test attribute "vehicles_count"
     */
    public function testPropertyVehiclesCount()
    {
    }

    /**
     * Test attribute "kpo_card_number"
     */
    public function testPropertyKpoCardNumber()
    {
    }

    /**
     * Test attribute "created_by_user"
     */
    public function testPropertyCreatedByUser()
    {
    }
}
