<?php
/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterElectronicWasteRecordCardV1UpdateKezsWasteManagementHandedOverRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterElectronicWasteRecordCardV1UpdateKezsWasteManagementHandedOverRequestTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsRequestsWasteRegisterElectronicWasteRecordCardV1UpdateKezsWasteManagementHandedOverRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsRequestsWasteRegisterElectronicWasteRecordCardV1UpdateKezsWasteManagementHandedOverRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsRequestsWasteRegisterElectronicWasteRecordCardV1UpdateKezsWasteManagementHandedOverRequest"
     */
    public function testWasteRegisterPublicApiApiModelsRequestsWasteRegisterElectronicWasteRecordCardV1UpdateKezsWasteManagementHandedOverRequest()
    {
    }

    /**
     * Test attribute "kezs_waste_management_handed_over_id"
     */
    public function testPropertyKezsWasteManagementHandedOverId()
    {
    }

    /**
     * Test attribute "waste_code_id"
     */
    public function testPropertyWasteCodeId()
    {
    }

    /**
     * Test attribute "kpo_id"
     */
    public function testPropertyKpoId()
    {
    }

    /**
     * Test attribute "kpok_id"
     */
    public function testPropertyKpokId()
    {
    }

    /**
     * Test attribute "kpo_handover_date"
     */
    public function testPropertyKpoHandoverDate()
    {
    }

    /**
     * Test attribute "waste_process_id"
     */
    public function testPropertyWasteProcessId()
    {
    }

    /**
     * Test attribute "waste_mass"
     */
    public function testPropertyWasteMass()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "locality"
     */
    public function testPropertyLocality()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "building_number"
     */
    public function testPropertyBuildingNumber()
    {
    }

    /**
     * Test attribute "local_number"
     */
    public function testPropertyLocalNumber()
    {
    }

    /**
     * Test attribute "waste_transport_start_date"
     */
    public function testPropertyWasteTransportStartDate()
    {
    }

    /**
     * Test attribute "is_salvage_waste_process"
     */
    public function testPropertyIsSalvageWasteProcess()
    {
    }

    /**
     * Test attribute "is_recycling"
     */
    public function testPropertyIsRecycling()
    {
    }

    /**
     * Test attribute "is_entry_based_on_kpo"
     */
    public function testPropertyIsEntryBasedOnKpo()
    {
    }

    /**
     * Test attribute "is_entry_based_on_kpok"
     */
    public function testPropertyIsEntryBasedOnKpok()
    {
    }

    /**
     * Test attribute "is_export_from_rp"
     */
    public function testPropertyIsExportFromRp()
    {
    }

    /**
     * Test attribute "is_equipment_owner_exempt_from_record"
     */
    public function testPropertyIsEquipmentOwnerExemptFromRecord()
    {
    }

    /**
     * Test attribute "is_handed_over"
     */
    public function testPropertyIsHandedOver()
    {
    }

    /**
     * Test attribute "additional_information"
     */
    public function testPropertyAdditionalInformation()
    {
    }

    /**
     * Test attribute "transport_type"
     */
    public function testPropertyTransportType()
    {
    }

    /**
     * Test attribute "waste_code_extended"
     */
    public function testPropertyWasteCodeExtended()
    {
    }

    /**
     * Test attribute "waste_code_extended_description"
     */
    public function testPropertyWasteCodeExtendedDescription()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification"
     */
    public function testPropertyHazardousWasteReclassification()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification_description"
     */
    public function testPropertyHazardousWasteReclassificationDescription()
    {
    }
}
