<?php
/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1GetKeokResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1GetKeokResponseTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1GetKeokResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1GetKeokResponseTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1GetKeokResponse"
     */
    public function testWasteRegisterPublicApiApiModelsResponsesWasteRegisterMuncipalWasteRecordCardV1GetKeokResponse()
    {
    }

    /**
     * Test attribute "keok_id"
     */
    public function testPropertyKeokId()
    {
    }

    /**
     * Test attribute "eup_id"
     */
    public function testPropertyEupId()
    {
    }

    /**
     * Test attribute "card_number"
     */
    public function testPropertyCardNumber()
    {
    }

    /**
     * Test attribute "waste_code_id"
     */
    public function testPropertyWasteCodeId()
    {
    }

    /**
     * Test attribute "waste_code"
     */
    public function testPropertyWasteCode()
    {
    }

    /**
     * Test attribute "waste_code_name"
     */
    public function testPropertyWasteCodeName()
    {
    }

    /**
     * Test attribute "year"
     */
    public function testPropertyYear()
    {
    }

    /**
     * Test attribute "waste_origin_teryt_id"
     */
    public function testPropertyWasteOriginTerytId()
    {
    }

    /**
     * Test attribute "waste_origin_address_html"
     */
    public function testPropertyWasteOriginAddressHtml()
    {
    }

    /**
     * Test attribute "waste_origin_address_formatted"
     */
    public function testPropertyWasteOriginAddressFormatted()
    {
    }

    /**
     * Test attribute "initial_waste_mass"
     */
    public function testPropertyInitialWasteMass()
    {
    }

    /**
     * Test attribute "is_waste_receive"
     */
    public function testPropertyIsWasteReceive()
    {
    }

    /**
     * Test attribute "is_waste_collecting"
     */
    public function testPropertyIsWasteCollecting()
    {
    }

    /**
     * Test attribute "is_salvage"
     */
    public function testPropertyIsSalvage()
    {
    }

    /**
     * Test attribute "is_neutralization"
     */
    public function testPropertyIsNeutralization()
    {
    }

    /**
     * Test attribute "can_be_edited"
     */
    public function testPropertyCanBeEdited()
    {
    }

    /**
     * Test attribute "waste_code_extended"
     */
    public function testPropertyWasteCodeExtended()
    {
    }

    /**
     * Test attribute "waste_code_extended_description"
     */
    public function testPropertyWasteCodeExtendedDescription()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification"
     */
    public function testPropertyHazardousWasteReclassification()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification_description"
     */
    public function testPropertyHazardousWasteReclassificationDescription()
    {
    }
}
