<?php
/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleReceivedVehicleV1CreateDismantleReceivedVehicleRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleReceivedVehicleV1CreateDismantleReceivedVehicleRequestTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleReceivedVehicleV1CreateDismantleReceivedVehicleRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleReceivedVehicleV1CreateDismantleReceivedVehicleRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleReceivedVehicleV1CreateDismantleReceivedVehicleRequest"
     */
    public function testWasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleReceivedVehicleV1CreateDismantleReceivedVehicleRequest()
    {
    }

    /**
     * Test attribute "received_from_dismantle_station"
     */
    public function testPropertyReceivedFromDismantleStation()
    {
    }

    /**
     * Test attribute "kepw_id"
     */
    public function testPropertyKepwId()
    {
    }

    /**
     * Test attribute "receive_date"
     */
    public function testPropertyReceiveDate()
    {
    }

    /**
     * Test attribute "vehicles_mass"
     */
    public function testPropertyVehiclesMass()
    {
    }

    /**
     * Test attribute "vehicles_count"
     */
    public function testPropertyVehiclesCount()
    {
    }

    /**
     * Test attribute "kpo_id"
     */
    public function testPropertyKpoId()
    {
    }

    /**
     * Test attribute "received_with_kpo"
     */
    public function testPropertyReceivedWithKpo()
    {
    }

    /**
     * Test attribute "received_from_abroad"
     */
    public function testPropertyReceivedFromAbroad()
    {
    }

    /**
     * Test attribute "owner_not_registered"
     */
    public function testPropertyOwnerNotRegistered()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "locality"
     */
    public function testPropertyLocality()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "building_number"
     */
    public function testPropertyBuildingNumber()
    {
    }

    /**
     * Test attribute "local_number"
     */
    public function testPropertyLocalNumber()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "additional_info"
     */
    public function testPropertyAdditionalInfo()
    {
    }
}
