<?php
/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleTransferredWasteV1UpdateDismantleTransferredWasteRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleTransferredWasteV1UpdateDismantleTransferredWasteRequestTest Class Doc Comment
 *
 * @category    Class
 * @description WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleTransferredWasteV1UpdateDismantleTransferredWasteRequest
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleTransferredWasteV1UpdateDismantleTransferredWasteRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "WasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleTransferredWasteV1UpdateDismantleTransferredWasteRequest"
     */
    public function testWasteRegisterPublicApiApiModelsRequestsWasteRegisterWreckWasteRecordCardDismantleTransferredWasteV1UpdateDismantleTransferredWasteRequest()
    {
    }

    /**
     * Test attribute "kepw_dismantle_transferred_waste_id"
     */
    public function testPropertyKepwDismantleTransferredWasteId()
    {
    }

    /**
     * Test attribute "waste_code_id"
     */
    public function testPropertyWasteCodeId()
    {
    }

    /**
     * Test attribute "kpo_id"
     */
    public function testPropertyKpoId()
    {
    }

    /**
     * Test attribute "recycled_waste_mass"
     */
    public function testPropertyRecycledWasteMass()
    {
    }

    /**
     * Test attribute "energy_recovery_waste_mass"
     */
    public function testPropertyEnergyRecoveryWasteMass()
    {
    }

    /**
     * Test attribute "other_than_recycled_waste_mass"
     */
    public function testPropertyOtherThanRecycledWasteMass()
    {
    }

    /**
     * Test attribute "shredded_waste_mass"
     */
    public function testPropertyShreddedWasteMass()
    {
    }

    /**
     * Test attribute "disposed_waste_mass"
     */
    public function testPropertyDisposedWasteMass()
    {
    }

    /**
     * Test attribute "additional_info"
     */
    public function testPropertyAdditionalInfo()
    {
    }

    /**
     * Test attribute "transferred_abroad"
     */
    public function testPropertyTransferredAbroad()
    {
    }

    /**
     * Test attribute "transferred_abroad_recycled"
     */
    public function testPropertyTransferredAbroadRecycled()
    {
    }

    /**
     * Test attribute "transferred_abroad_waste_mass"
     */
    public function testPropertyTransferredAbroadWasteMass()
    {
    }

    /**
     * Test attribute "transferred_abroad_transfer_date"
     */
    public function testPropertyTransferredAbroadTransferDate()
    {
    }

    /**
     * Test attribute "transferred_abroad_waste_process_id"
     */
    public function testPropertyTransferredAbroadWasteProcessId()
    {
    }

    /**
     * Test attribute "country_id"
     */
    public function testPropertyCountryId()
    {
    }

    /**
     * Test attribute "locality"
     */
    public function testPropertyLocality()
    {
    }

    /**
     * Test attribute "street"
     */
    public function testPropertyStreet()
    {
    }

    /**
     * Test attribute "building_number"
     */
    public function testPropertyBuildingNumber()
    {
    }

    /**
     * Test attribute "local_number"
     */
    public function testPropertyLocalNumber()
    {
    }

    /**
     * Test attribute "postal_code"
     */
    public function testPropertyPostalCode()
    {
    }

    /**
     * Test attribute "is_road_transport"
     */
    public function testPropertyIsRoadTransport()
    {
    }

    /**
     * Test attribute "is_railway_transport"
     */
    public function testPropertyIsRailwayTransport()
    {
    }

    /**
     * Test attribute "is_maritime_transport"
     */
    public function testPropertyIsMaritimeTransport()
    {
    }

    /**
     * Test attribute "is_air_transport"
     */
    public function testPropertyIsAirTransport()
    {
    }

    /**
     * Test attribute "is_inland_water_transport"
     */
    public function testPropertyIsInlandWaterTransport()
    {
    }

    /**
     * Test attribute "waste_code_extended"
     */
    public function testPropertyWasteCodeExtended()
    {
    }

    /**
     * Test attribute "waste_code_extended_description"
     */
    public function testPropertyWasteCodeExtendedDescription()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification"
     */
    public function testPropertyHazardousWasteReclassification()
    {
    }

    /**
     * Test attribute "hazardous_waste_reclassification_description"
     */
    public function testPropertyHazardousWasteReclassificationDescription()
    {
    }

    /**
     * Test attribute "waste_mass_from_kpo"
     */
    public function testPropertyWasteMassFromKpo()
    {
    }
}
