<?php
/**
 * KeonApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * v1 Waste Register public Api
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use \Swagger\Client\Configuration;
use \Swagger\Client\ApiException;
use \Swagger\Client\ObjectSerializer;

/**
 * KeonApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class KeonApiTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createKeon
     *
     * Tworzenie karty.
     *
     */
    public function testCreateKeon()
    {
    }

    /**
     * Test case for createKeonItem
     *
     * Tworzenie wpisu.
     *
     */
    public function testCreateKeonItem()
    {
    }

    /**
     * Test case for deleteKeon
     *
     * Usunięcie karty.
     *
     */
    public function testDeleteKeon()
    {
    }

    /**
     * Test case for deleteKeonItem
     *
     * Usunięcie wpisu.
     *
     */
    public function testDeleteKeonItem()
    {
    }

    /**
     * Test case for editKeonItem
     *
     * Edycja wpisu.
     *
     */
    public function testEditKeonItem()
    {
    }

    /**
     * Test case for getKeon
     *
     * Informacje o karcie.
     *
     */
    public function testGetKeon()
    {
    }

    /**
     * Test case for getKeonItem
     *
     * Informacje o wpisie.
     *
     */
    public function testGetKeonItem()
    {
    }

    /**
     * Test case for getKeonPrintingPageData
     *
     * Pobranie danych karty do wydruku.
     *
     */
    public function testGetKeonPrintingPageData()
    {
    }

    /**
     * Test case for getKeonSummary
     *
     * Zestawienie danych.
     *
     */
    public function testGetKeonSummary()
    {
    }

    /**
     * Test case for getKeonWithKeonItems
     *
     * Lista wpisów.
     *
     */
    public function testGetKeonWithKeonItems()
    {
    }

    /**
     * Test case for searchKeon
     *
     * Wyszukiwarka kart.
     *
     */
    public function testSearchKeon()
    {
    }

    /**
     * Test case for searchKeonItems
     *
     * Wyszukiwarka wpisów.
     *
     */
    public function testSearchKeonItems()
    {
    }
}
